@startuml State Diagram Game Day
skinparam monochrome true

[*] --> Начало : Инициализация
Начало --> Диалог : Загрузка диалогов
Диалог --> Выбор : Пользовательский ввод
Выбор --> Мини_игра : Переход к задаче
Мини_игра --> Конец_дня : Завершение задачи
Конец_дня --> [*] : Сохранение и переход
@enduml 